### ISSUE TITLE
Help with error "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by hudovisk** [MeltanoLabs/tap-bigquery#22]
Hey everyone, we started having the following error in the extraction process:

```
2024-06-26T15:51:31.158227Z [info     ] 2024-06-26 15:51:31,153 | INFO     | singer_sdk.metrics   | METRIC: {"type": "counter", "metric": "record_count", "value": 1760, "tags": {"stream": "analytics_XXXXXX-google_analytics_events", "context": {}}} cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.162109Z [info     ] 2024-06-26 15:51:31,153 | ERROR    | tap-bigquery         | An unhandled error occurred while syncing 'analytics_XXXXXXX-google_analytics_events' cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.163084Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.163885Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1179, in sync cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.164894Z [info     ]     for _ in self._sync_records(context=context): cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.166596Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1101, in _sync_records cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.167851Z [info     ]     self._write_record_message(record) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.168945Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 843, in _write_record_message cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.170596Z [info     ]     for record_message in self._generate_record_messages(record): cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.171190Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 827, in _generate_record_messages cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.173174Z [info     ]     mapped_record = stream_map.transform(record) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.174057Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/mapper.py", line 280, in transform cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.174773Z [info     ]     transformed_record = self._transform_fn(record) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.176564Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/mapper.py", line 559, in transform_fn cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.177852Z [info     ]     result[prop_key] = self._eval( cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.178626Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/mapper.py", line 336, in _eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.179083Z [info     ]     result: str | int | float = simpleeval.simple_eval( cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.180170Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 679, in simple_eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.181294Z [info     ]     return s.eval(expr)        cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.182229Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 376, in eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.183711Z [info     ]     return self._eval(ast.parse(expr.strip()).body[0]) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.184475Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 389, in _eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.186123Z [info     ]     return handler(node)       cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.187473Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 392, in _eval_expr cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.189172Z [info     ]     return self._eval(node.value) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.190067Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 389, in _eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.191884Z [info     ]     return handler(node)       cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.192857Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 523, in _eval_subscript cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.194288Z [info     ]     return container[key]      cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.195615Z [info     ] TypeError: 'NoneType' object is not subscriptable cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.197111Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.198029Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/bin/tap-bigquery", line 8, in <module> cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.199377Z [info     ]     sys.exit(TapBigQuery.cli()) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.200170Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__ cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.201097Z [info     ]     return self.main(*args, **kwargs) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.201781Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.202385Z [info     ]     rv = self.invoke(ctx)      cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.203144Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.203755Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.204497Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.205195Z [info     ]     return __callback(*args, **kwargs) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.205790Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 500, in invoke cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.206383Z [info     ]     tap.sync_all()             cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.206893Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 459, in sync_all cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.207395Z [info     ]     stream.sync()              cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.208332Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1186, in sync cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.209000Z [info     ]     raise ex                   cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.209515Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1179, in sync cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.210149Z [info     ]     for _ in self._sync_records(context=context): cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.210756Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1101, in _sync_records cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.211311Z [info     ]     self._write_record_message(record) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.211885Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 843, in _write_record_message cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.212747Z [info     ]     for record_message in self._generate_record_messages(record): cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.213370Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 827, in _generate_record_messages cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.213927Z [info     ]     mapped_record = stream_map.transform(record) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.214425Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/mapper.py", line 280, in transform cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.215003Z [info     ]     transformed_record = self._transform_fn(record) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.215827Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/mapper.py", line 559, in transform_fn cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.216525Z [info     ]     result[prop_key] = self._eval( cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.217228Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/mapper.py", line 336, in _eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.217930Z [info     ]     result: str | int | float = simpleeval.simple_eval( cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.218622Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 679, in simple_eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.219213Z [info     ]     return s.eval(expr)        cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.219911Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 376, in eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.220523Z [info     ]     return self._eval(ast.parse(expr.strip()).body[0]) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.221139Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 389, in _eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.222155Z [info     ]     return handler(node)       cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.223157Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 392, in _eval_expr cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.224083Z [info     ]     return self._eval(node.value) cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.224622Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 389, in _eval cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.225460Z [info     ]     return handler(node)       cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.225943Z [info     ]   File "/project/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/singer_sdk/helpers/_simpleeval.py", line 523, in _eval_subscript cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.226617Z [info     ]     return container[key]      cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:31.227591Z [info     ] TypeError: 'NoneType' object is not subscriptable cmd_type=elb consumer=False name=tap-bigquery producer=True stdio=stderr string_id=tap-bigquery
2024-06-26T15:51:32.781838Z [info     ] time=2024-06-26 15:51:32 name=target_postgres level=INFO message=Loading 1760 rows into 'bigquery."ga_events"' cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-06-26T15:51:37.766837Z [info     ] time=2024-06-26 15:51:36 name=target_postgres level=INFO message=Loading into bigquery."ga_events": {"inserts": 264, "updates": 1496, "size_bytes": 3683946} cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-06-26T15:51:42.121356Z [info     ] Incremental state has been updated at 2024-06-26 15:51:42.120293.
2024-06-26T15:51:42.124734Z [info     ] {"bookmarks": {"analytics_XXXXXXX-google_analytics_events": {"replication_key": "event_timestamp", "replication_key_value": 1718679138359842}}} cmd_type=elb consumer=True name=target-postgres producer=False stdio=stdout string_id=target-postgres
2024-06-26T15:51:45.020244Z [error    ] Extractor failed
2024-06-26T15:51:45.032898Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Extractor failed') exit_codes={<PluginType.EXTRACTORS: 'extractors'>: 1} set_number=0 success=False
```

My meltano.yml is the following:

```yaml
- name: tap-bigquery
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-bigquery.git
      config:
        project_id: salvy-production
        credentials_path: /secrets/bigquery.json
        stream_maps:
          analytics_XXXXXX-google_analytics_events:
            __alias__: ga_events
            traffic_source__name: record['traffic_source']['name']
            traffic_source__source: record['traffic_source']['source']
            traffic_source__medium: record['traffic_source']['medium']
            event_params: record['event_params']
            __key_properties__:
              - user_pseudo_id
              - event_name
              - event_timestamp
      load_schema: bigquery
      select:
        - analytics_XXXXXX-google_analytics_events.user_pseudo_id
        - analytics_XXXXXX-google_analytics_events.event_name
        - analytics_XXXXXX-google_analytics_events.event_timestamp
        - analytics_XXXXXX-google_analytics_events.traffic_source
        - analytics_XXXXXX-google_analytics_events.user_id
        - analytics_XXXXXX-google_analytics_events.event_params
      metadata:
        analytics_XXXXXX-google_analytics_events:
          replication-method: INCREMENTAL
          replication-key: event_timestamp
          event_timestamp:
            is-replication-key: true
```

I run it with: `meltano run tap-bigquery target-postgres`

Does anyone have a clue or further guidance on how I could troubleshoot it? Thanks!

**Comment by edgarrmondragon** [comment]
Hey @hudovisk!

I don't think this is a bug in this tap and instead one of the things you're trying to index here is coming in as `None` instead of the dictionary you expect:

```yaml
traffic_source__name: record['traffic_source']['name']
traffic_source__source: record['traffic_source']['source']
traffic_source__medium: record['traffic_source']['medium']
```

I think you could use the ternary operator to work around it:

```yaml
traffic_source__name: record['traffic_source']['name'] if record['traffic_source'] else None
```

And so on.

**Comment by hudovisk** [comment]
Thanks @edgarrmondragon, you nailed it! I will close it since it is not related to the tap.
